"""Shared paths and constants for the trace-replay ContextSegmentKV harness."""
from __future__ import annotations

from pathlib import Path

# .../scripts/05_context_segment_agent_kv/core/config.py -> repo root
ROOT = Path(__file__).resolve().parents[3]
TRACES_DIR = ROOT / "src" / "traces"

DEFAULT_TASKS = [
    "internal_comms_incident_update",
    "doc_coauthoring_design_doc",
    "mcp_server_and_spec",
    "web_artifact_with_theme",
    "launch_poster_page_pack",
    "slack_launch_pack",
]

# Precomputed skill segment token locations per task, baked in so the replay
# harness need not re-run trace_skill_token_loc.py / re-read its JSON output.
#
# Provenance: generated by replay/trace_skill_token_loc.py from each task's
# final cumulative trace (trace_file below), against model "Qwen3" via the
# modified vLLM /tokenize endpoint, with an EMPTY --system-prefix and
# enable_thinking=True. Token positions are exact: every skill segment wraps
# the whole tool message (char span starts at 0), so both span boundaries fall
# on clean token boundaries.
#
# IMPORTANT: these absolute token positions are tied to (a) the tokenizer +
# chat template of the served model, (b) the _system_prompt.txt / _tools.json
# under src/traces/, and (c) an empty system prefix. If any of those change,
# regenerate this table (do not hand-edit). Per skill: "tokens" is the segment
# length, "token_spans" are [start, end) offsets into the full replay prompt
# (which includes the system message at index 0), and "message_indices" are the
# matching positions in the converted OpenAI message list.
SKILL_TOKEN_LOCATIONS: dict[str, dict] = {
    "internal_comms_incident_update": {
        "skills": {
            "internal-comms": {
                "tokens": 338,
                "message_indices": [3, 19, 37],
                "token_spans": [[4145, 4483], [5774, 6112], [8115, 8453]],
            },
        },
    },
    "doc_coauthoring_design_doc": {
        "skills": {
            "doc-coauthoring": {
                "tokens": 3313,
                "message_indices": [3, 21, 39],
                "token_spans": [[4168, 7481], [9196, 12509], [16981, 20294]],
            },
        },
    },
    "mcp_server_and_spec": {
        "skills": {
            "mcp-builder": {
                "tokens": 1918,
                "message_indices": [3, 15, 41],
                "token_spans": [[4164, 6082], [7017, 8935], [19362, 21280]],
            },
            "doc-coauthoring": {
                "tokens": 3313,
                "message_indices": [21, 27, 43],
                "token_spans": [[9559, 12872], [13643, 16956], [21353, 24666]],
            },
        },
    },
    "web_artifact_with_theme": {
        "skills": {
            "web-artifacts-builder": {
                "tokens": 719,
                "message_indices": [3, 15, 41],
                "token_spans": [[4171, 4890], [6053, 6772], [14161, 14880]],
            },
            "theme-factory": {
                "tokens": 669,
                "message_indices": [21, 27, 43],
                "token_spans": [[7604, 8273], [9568, 10237], [14950, 15619]],
            },
        },
    },
    "launch_poster_page_pack": {
        "skills": {
            "canvas-design": {
                "tokens": 2356,
                "message_indices": [3, 29, 45],
                "token_spans": [[4143, 6499], [11179, 13535], [16538, 18894]],
            },
            "web-artifacts-builder": {
                "tokens": 719,
                "message_indices": [11, 31, 47],
                "token_spans": [[7056, 7775], [13607, 14326], [18966, 19685]],
            },
            "theme-factory": {
                "tokens": 669,
                "message_indices": [21, 33, 49],
                "token_spans": [[9212, 9881], [14396, 15065], [19755, 20424]],
            },
        },
    },
    "slack_launch_pack": {
        "skills": {
            "internal-comms": {
                "tokens": 338,
                "message_indices": [3, 29, 47],
                "token_spans": [[4151, 4489], [8784, 9122], [13077, 13415]],
            },
            "slack-gif-creator": {
                "tokens": 2090,
                "message_indices": [15, 31, 49],
                "token_spans": [[5196, 7286], [9197, 11287], [13490, 15580]],
            },
            "brand-guidelines": {
                "tokens": 540,
                "message_indices": [21, 33, 51],
                "token_spans": [[7679, 8219], [11358, 11898], [15651, 16191]],
            },
        }, 
    },
}


def get_skill_token_span(task: str, skill: str, occurrence: int) -> tuple[int, int]:
    """Return the precomputed [start, end) token span for a skill occurrence."""
    try:
        skill_record = SKILL_TOKEN_LOCATIONS[task]["skills"][skill]
        start, end = skill_record["token_spans"][occurrence - 1]
    except KeyError as exc:
        raise KeyError(
            f"No configured token locations for task={task!r}, skill={skill!r}"
        ) from exc
    except IndexError as exc:
        raise IndexError(
            f"No configured token span for task={task!r}, skill={skill!r}, "
            f"occurrence={occurrence}"
        ) from exc
    return start, end
