"""Summarize boundary-candidate scoring coverage into case-level conclusions.

This script is offline-only. It reads the candidate coverage table generated by
build_boundary_candidate_review.py and produces one row per scored divergence
boundary. It does not fill in manual review; if manual columns are blank, the
summary marks the case as pending manual review.
"""
from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in __import__("sys").path:
    __import__("sys").path.insert(0, str(SCRIPT_DIR))

from config import RESULTS_DIR  # noqa: E402

DEFAULT_ROOT = RESULTS_DIR / "thinking_to_action_divergence"
DEFAULT_PAIR_CSV = DEFAULT_ROOT / "tables" / "thinking_pair_summary.csv"
DEFAULT_REVIEW_CSV = DEFAULT_ROOT / "tables" / "bc_case_manual_review.csv"
DEFAULT_PLAN_CSV = DEFAULT_ROOT / "tables" / "boundary_candidate_scoring_plan.csv"
DEFAULT_OUT_CSV = DEFAULT_ROOT / "tables" / "candidate_scoring_summary.csv"


def load_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, Any]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fields})


def case_key(row: dict[str, Any]) -> tuple[str, str, str]:
    return (str(row["task"]), str(row["skill"]), str(row["occurrence"]))


def full_key(row: dict[str, Any]) -> tuple[str, str, str, str]:
    return (
        str(row["task"]),
        str(row["skill"]),
        str(row["occurrence"]),
        str(row["invocation_index"]),
    )


def parse_action_tools(action_label: str) -> list[str]:
    label = (action_label or "").strip()
    if not label.startswith("tool:"):
        return []
    return [part.strip() for part in label[len("tool:") :].split("+") if part.strip()]


def action_modality(action_label: str) -> str:
    return "tool" if (action_label or "").startswith("tool:") else "text"


def first_action_tool(action_label: str) -> str | None:
    tools = parse_action_tools(action_label)
    return tools[0] if tools else None


def float_or_none(value: str | None) -> float | None:
    if value in (None, ""):
        return None
    return float(value)


def manual_status(review_rows: list[dict[str, str]]) -> str:
    values = [
        (row.get("manual_intent_matches_pair") or "").strip().lower()
        for row in review_rows
        if (row.get("manual_intent_matches_pair") or "").strip()
    ]
    if not values:
        return "pending"
    if any(value in {"false", "no", "0", "intent_drift"} for value in values):
        return "intent_drift_possible"
    if any(value in {"unclear", "unknown", "?"} or value.startswith("unclear") for value in values):
        return "unclear"
    if all(value in {"true", "yes", "1", "same"} for value in values):
        return "confirmed_similar"
    return "mixed_manual_labels"


def candidate_for_text_mode(
    plan_rows: list[dict[str, str]],
    *,
    mode: str,
) -> str | None:
    for row in plan_rows:
        if (
            row["mode"] == mode
            and row["candidate_group"] == "tool_text_boundary"
            and row["candidate_kind"] == "observed_text_token"
        ):
            return row["candidate"]
    return None


def row_for_candidate(
    plan_rows: list[dict[str, str]],
    *,
    mode: str,
    candidate_group: str,
    candidate: str,
) -> dict[str, str] | None:
    for row in plan_rows:
        if (
            row["mode"] == mode
            and row["candidate_group"] == candidate_group
            and row["candidate"] == candidate
        ):
            return row
    return None


def support_summary(row: dict[str, str] | None) -> tuple[str, str, str, str]:
    if row is None:
        return ("missing_plan_row", "", "", "")
    return (
        row.get("support_status") or "",
        row.get("candidate_rank") or "",
        row.get("candidate_logprob") or "",
        row.get("matched_token") or "",
    )


def compare_scores(
    left_name: str,
    left_logprob: float | None,
    right_name: str,
    right_logprob: float | None,
) -> str:
    if left_logprob is None or right_logprob is None:
        return "missing_candidate_score"
    if left_logprob > right_logprob:
        return f"{left_name}_higher"
    if right_logprob > left_logprob:
        return f"{right_name}_higher"
    return "tie"


def expected_supported(order: str, expected_candidate_label: str) -> bool:
    return order == f"{expected_candidate_label}_higher"


def evidence_label(
    *,
    order_at_recompute: str,
    order_at_rope: str,
    recompute_candidate_supported_in_recompute: bool,
    rope_candidate_supported_in_rope: bool,
    manual: str,
) -> str:
    if manual == "intent_drift_possible":
        return "intent_drift_possible"
    if manual == "unclear":
        return "manual_unclear"
    if expected_supported(order_at_recompute, "recompute_candidate") and expected_supported(
        order_at_rope, "rope_candidate"
    ):
        return "confirmed_boundary_flip"
    if "missing_candidate_score" in {order_at_recompute, order_at_rope}:
        if recompute_candidate_supported_in_recompute and rope_candidate_supported_in_rope:
            return "partial_boundary_flip_evidence"
        return "needs_forced_scoring"
    return "no_boundary_flip_evidence"


def make_summary_row(
    pair: dict[str, str],
    plan_rows: list[dict[str, str]],
    review_rows: list[dict[str, str]],
    *,
    candidate_group: str,
    recompute_candidate: str,
    rope_candidate: str,
) -> dict[str, Any]:
    rec_rec = row_for_candidate(
        plan_rows,
        mode="recompute",
        candidate_group=candidate_group,
        candidate=recompute_candidate,
    )
    rope_rec = row_for_candidate(
        plan_rows,
        mode="recompute",
        candidate_group=candidate_group,
        candidate=rope_candidate,
    )
    rec_rope = row_for_candidate(
        plan_rows,
        mode="rope",
        candidate_group=candidate_group,
        candidate=recompute_candidate,
    )
    rope_rope = row_for_candidate(
        plan_rows,
        mode="rope",
        candidate_group=candidate_group,
        candidate=rope_candidate,
    )

    rec_rec_status, rec_rec_rank, rec_rec_lp, rec_rec_token = support_summary(rec_rec)
    rope_rec_status, rope_rec_rank, rope_rec_lp, rope_rec_token = support_summary(rope_rec)
    rec_rope_status, rec_rope_rank, rec_rope_lp, rec_rope_token = support_summary(rec_rope)
    rope_rope_status, rope_rope_rank, rope_rope_lp, rope_rope_token = support_summary(rope_rope)

    rec_rec_logprob = float_or_none(rec_rec_lp)
    rope_rec_logprob = float_or_none(rope_rec_lp)
    rec_rope_logprob = float_or_none(rec_rope_lp)
    rope_rope_logprob = float_or_none(rope_rope_lp)

    order_at_recompute = compare_scores(
        "recompute_candidate",
        rec_rec_logprob,
        "rope_candidate",
        rope_rec_logprob,
    )
    order_at_rope = compare_scores(
        "recompute_candidate",
        rec_rope_logprob,
        "rope_candidate",
        rope_rope_logprob,
    )
    manual = manual_status(review_rows)
    label = evidence_label(
        order_at_recompute=order_at_recompute,
        order_at_rope=order_at_rope,
        recompute_candidate_supported_in_recompute=rec_rec_logprob is not None,
        rope_candidate_supported_in_rope=rope_rope_logprob is not None,
        manual=manual,
    )

    return {
        "task": pair["task"],
        "skill": pair["skill"],
        "occurrence": pair["occurrence"],
        "invocation_index": pair["invocation_index"],
        "category": pair["category"],
        "manual_status": manual,
        "divergence_group": candidate_group,
        "recompute_action": pair["recompute_action"],
        "rope_action": pair["rope_action"],
        "recompute_candidate": recompute_candidate,
        "rope_candidate": rope_candidate,
        "recompute_candidate_support_at_recompute": rec_rec_status,
        "recompute_candidate_rank_at_recompute": rec_rec_rank,
        "recompute_candidate_logprob_at_recompute": rec_rec_lp,
        "recompute_candidate_token_at_recompute": rec_rec_token,
        "rope_candidate_support_at_recompute": rope_rec_status,
        "rope_candidate_rank_at_recompute": rope_rec_rank,
        "rope_candidate_logprob_at_recompute": rope_rec_lp,
        "rope_candidate_token_at_recompute": rope_rec_token,
        "recompute_candidate_support_at_rope": rec_rope_status,
        "recompute_candidate_rank_at_rope": rec_rope_rank,
        "recompute_candidate_logprob_at_rope": rec_rope_lp,
        "recompute_candidate_token_at_rope": rec_rope_token,
        "rope_candidate_support_at_rope": rope_rope_status,
        "rope_candidate_rank_at_rope": rope_rope_rank,
        "rope_candidate_logprob_at_rope": rope_rope_lp,
        "rope_candidate_token_at_rope": rope_rope_token,
        "order_at_recompute_boundary": order_at_recompute,
        "order_at_rope_boundary": order_at_rope,
        "score_gap_at_recompute_boundary": (
            rec_rec_logprob - rope_rec_logprob
            if rec_rec_logprob is not None and rope_rec_logprob is not None
            else ""
        ),
        "score_gap_at_rope_boundary": (
            rope_rope_logprob - rec_rope_logprob
            if rope_rope_logprob is not None and rec_rope_logprob is not None
            else ""
        ),
        "evidence_label": label,
        "needs_forced_scoring": label == "needs_forced_scoring",
    }


def build_rows(
    pairs: list[dict[str, str]],
    plan_rows_by_key: dict[tuple[str, str, str, str], list[dict[str, str]]],
    review_rows_by_key: dict[tuple[str, str, str, str], list[dict[str, str]]],
) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for pair in pairs:
        key = full_key(pair)
        plan_rows = plan_rows_by_key.get(key, [])
        reviews = review_rows_by_key.get(key, [])
        rec_action = pair["recompute_action"]
        rope_action = pair["rope_action"]

        if action_modality(rec_action) != action_modality(rope_action):
            rec_candidate = (
                "<tool_call>"
                if action_modality(rec_action) == "tool"
                else candidate_for_text_mode(plan_rows, mode="recompute")
            )
            rope_candidate = (
                "<tool_call>"
                if action_modality(rope_action) == "tool"
                else candidate_for_text_mode(plan_rows, mode="rope")
            )
            if rec_candidate and rope_candidate:
                out.append(
                    make_summary_row(
                        pair,
                        plan_rows,
                        reviews,
                        candidate_group="tool_text_boundary",
                        recompute_candidate=rec_candidate,
                        rope_candidate=rope_candidate,
                    )
                )

        rec_tool = first_action_tool(rec_action)
        rope_tool = first_action_tool(rope_action)
        if rec_tool and rope_tool and rec_tool != rope_tool:
            out.append(
                make_summary_row(
                    pair,
                    plan_rows,
                    reviews,
                    candidate_group="function_name_boundary",
                    recompute_candidate=rec_tool,
                    rope_candidate=rope_tool,
                )
            )
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pair-csv", type=Path, default=DEFAULT_PAIR_CSV)
    parser.add_argument("--review-csv", type=Path, default=DEFAULT_REVIEW_CSV)
    parser.add_argument("--plan-csv", type=Path, default=DEFAULT_PLAN_CSV)
    parser.add_argument("--out-csv", type=Path, default=DEFAULT_OUT_CSV)
    args = parser.parse_args()

    pairs = [
        row
        for row in load_csv(args.pair_csv)
        if row.get("category")
        in {"B_thinking_similar_action_diverged", "C_thinking_different_action_diverged"}
    ]
    plan_rows_by_key: dict[tuple[str, str, str, str], list[dict[str, str]]] = defaultdict(list)
    for row in load_csv(args.plan_csv):
        plan_rows_by_key[full_key(row)].append(row)
    review_rows_by_key: dict[tuple[str, str, str, str], list[dict[str, str]]] = defaultdict(list)
    for row in load_csv(args.review_csv):
        review_rows_by_key[full_key(row)].append(row)

    rows = build_rows(pairs, plan_rows_by_key, review_rows_by_key)
    fields = [
        "task",
        "skill",
        "occurrence",
        "invocation_index",
        "category",
        "manual_status",
        "divergence_group",
        "recompute_action",
        "rope_action",
        "recompute_candidate",
        "rope_candidate",
        "recompute_candidate_support_at_recompute",
        "recompute_candidate_rank_at_recompute",
        "recompute_candidate_logprob_at_recompute",
        "recompute_candidate_token_at_recompute",
        "rope_candidate_support_at_recompute",
        "rope_candidate_rank_at_recompute",
        "rope_candidate_logprob_at_recompute",
        "rope_candidate_token_at_recompute",
        "recompute_candidate_support_at_rope",
        "recompute_candidate_rank_at_rope",
        "recompute_candidate_logprob_at_rope",
        "recompute_candidate_token_at_rope",
        "rope_candidate_support_at_rope",
        "rope_candidate_rank_at_rope",
        "rope_candidate_logprob_at_rope",
        "rope_candidate_token_at_rope",
        "order_at_recompute_boundary",
        "order_at_rope_boundary",
        "score_gap_at_recompute_boundary",
        "score_gap_at_rope_boundary",
        "evidence_label",
        "needs_forced_scoring",
    ]
    write_csv(args.out_csv, rows, fields)
    counts: dict[str, int] = defaultdict(int)
    for row in rows:
        counts[str(row["evidence_label"])] += 1
    print(f"Wrote {args.out_csv} ({len(rows)} rows)")
    for label, count in sorted(counts.items()):
        print(f"{label}: {count}")


if __name__ == "__main__":
    main()
